# Generated by Django 4.2 on 2023-05-04 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eecommerceapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(default='', max_length=100)),
                ('image', models.FileField(blank=True, default='', null=True, upload_to='image')),
                ('price', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
