# Generated by Django 4.2 on 2023-05-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eecommerceapp', '0002_p_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_user',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
                ('phone_no', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
