# Generated by Django 4.2 on 2023-05-05 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eecommerceapp', '0003_p_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eecommerceapp.p_product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eecommerceapp.p_user')),
            ],
        ),
    ]
